-- DEVELOPER roles grants
GRANT CONNECT TO "DEVELOPER";
GRANT RESOURCE TO "DEVELOPER";
GRANT CREATE TABLE TO "DEVELOPER";
GRANT CREATE VIEW TO "DEVELOPER";
GRANT CREATE TYPE TO "DEVELOPER";
GRANT CREATE SEQUENCE TO "DEVELOPER";
GRANT CREATE PROCEDURE TO "DEVELOPER";
GRANT CREATE TRIGGER TO "DEVELOPER";
GRANT CREATE SYNONYM TO "DEVELOPER";
GRANT CREATE PUBLIC SYNONYM TO "DEVELOPER";
GRANT EXECUTE ON DBMS_CRYPTO TO "DEVELOPER";
GRANT EXECUTE ON DBMS_RANDOM TO "DEVELOPER";


-- Grant DEVELOPER Role to SHOP_DEV
GRANT "DEVELOPER" TO "SHOP_DEV";
