-- Create DEVELOPER Role
CREATE ROLE "DEVELOPER";


-- Create DEVELOPER User
CREATE USER "SHOP_DEV" IDENTIFIED BY "kamel"
DEFAULT TABLESPACE "ONLINE_SHOP_TS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER "SHOP_DEV" QUOTA UNLIMITED ON "ONLINE_SHOP_TS";

CREATE TABLESPACE SUPER_USER_TS 
    DATAFILE 
        'C:\APP\KAMEL\PRODUCT\21C\ORADATA\XE\ONLINE_SHOP_PDB\SUPER_USER_TS.DBF' 
        SIZE 1048576000 AUTOEXTEND ON NEXT 1258291200 MAXSIZE 2097152000;

-- USER SQL
ALTER USER "SUPER_ADMIN"
DEFAULT TABLESPACE "SUPER_USER_TS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "SUPER_ADMIN" QUOTA UNLIMITED ON "SUPER_USER_TS";
