-- Create DEVELOPER Role
CREATE ROLE "DEVELOPER";


-- Create DEVELOPER User
CREATE USER "SHOP_DEV" IDENTIFIED BY "kamel"
DEFAULT TABLESPACE "ONLINE_SHOP_TS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER "SHOP_DEV" QUOTA UNLIMITED ON "ONLINE_SHOP_TS";
