---
-- SEQUENCES
---

--- USERS
CREATE SEQUENCE seq_user_id
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE seq_user_num
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- PRODUCTS
CREATE SEQUENCE seq_product_id
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE seq_product_num
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- SHIPMENTS
CREATE SEQUENCE seq_shipment_id
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ORDERS
CREATE SEQUENCE seq_order_id
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
