ALTER PLUGGABLE DATABASE ONLINE_SHOP_PDB CLOSE IMMEDIATE;

ALTER PLUGGABLE DATABASE ONLINE_SHOP_PDB
  UNPLUG INTO 'C:\oracle_backups\clone\ONLINE_SHOP_PDB.xml';

DROP PLUGGABLE DATABASE ONLINE_SHOP_PDB KEEP DATAFILES;

CREATE PLUGGABLE DATABASE ONLINE_SHOP_PDB_CLONE
  USING 'C:\oracle_backups\clone\ONLINE_SHOP_PDB.xml'
  FILE_NAME_CONVERT = (
    'C:\app\kamel\product\21c\oradata\XE\ONLINE_SHOP_PDB',
    'C:\app\kamel\product\21c\oradata\XE\ONLINE_SHOP_PDB_CLONE'
  );

ALTER PLUGGABLE DATABASE ONLINE_SHOP_PDB_CLONE OPEN;

EXIT;
