ALTER PLUGGABLE DATABASE ONLINE_SHOP_PDB CLOSE IMMEDIATE;

ALTER PLUGGABLE DATABASE ONLINE_SHOP_PDB
  UNPLUG INTO 'Z:\clone\ONLINE_SHOP_PDB.xml';

DROP PLUGGABLE DATABASE ONLINE_SHOP_PDB KEEP DATAFILES;

CREATE PLUGGABLE DATABASE ONLINE_SHOP_PDB_CLONE
  USING 'Z:\clone\ONLINE_SHOP_PDB.xml'
  FILE_NAME_CONVERT = (
    'C:\app\Administrator\product\21c\oradata\XE\ONLINE_SHOP_PDB',
    'C:\app\Administrator\product\21c\oradata\XE\ONLINE_SHOP_PDB_CLONE'
  );

ALTER PLUGGABLE DATABASE ONLINE_SHOP_PDB_CLONE OPEN;

EXIT;
